import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/myComponents/ScrolltoTop";
import WhatsAppButton from "@/myComponents/Whatsapp";
import { cormorant } from "@/lib/fonts";
import Navbar from "@/myComponents/Navbar";
import Footer from "@/myComponents/Footer";

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.className} ${cormorant.variable} h-full antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <ScrollToTop />
        <WhatsAppButton />
        {children}
        <Footer />
      </body>
    </html>
  );
}
